#!/usr/bin/env python3
"""
Generate a valid ML-KEM-768 public key for the nRF54L15 transport demo.

Only the public key is written to the firmware header.
The secret key is intentionally NOT persisted because the current DK firmware
does not perform ML-KEM decapsulation on-chip.

Usage:
    python scripts/generate_firmware_public_key.py
    python scripts/generate_firmware_public_key.py --force
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.common.constants import PK_SIZE  # noqa: E402
from src.common.ml_kem import generate_keypair  # noqa: E402


DEFAULT_OUTPUT = (
    REPO_ROOT
    / "firmware"
    / "nrf54l15_pq_gatt_skeleton"
    / "src"
    / "demo_public_key.h"
)


def format_c_array(data: bytes, values_per_line: int = 12) -> str:
    lines: list[str] = []

    for offset in range(0, len(data), values_per_line):
        chunk = data[offset : offset + values_per_line]
        values = ", ".join(f"0x{value:02X}" for value in chunk)
        suffix = "," if offset + values_per_line < len(data) else ""
        lines.append(f"    {values}{suffix}")

    return "\n".join(lines)


def build_header(public_key: bytes, fingerprint: str) -> str:
    array = format_c_array(public_key)

    return f"""#ifndef PQ_BLE_DEMO_PUBLIC_KEY_H_
#define PQ_BLE_DEMO_PUBLIC_KEY_H_

/*
 * Generated by scripts/generate_firmware_public_key.py.
 *
 * This is a syntactically valid ML-KEM-768 public key.
 * SHA-256 fingerprint:
 * {fingerprint}
 *
 * The corresponding secret key is intentionally not stored.
 * Therefore, the current nRF54L15 firmware still validates only the
 * BLE/GATT transport path and cannot decapsulate the central ciphertext.
 */

static const uint8_t demo_pk[{len(public_key)}] = {{
{array}
}};

#endif /* PQ_BLE_DEMO_PUBLIC_KEY_H_ */
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a valid ML-KEM-768 public key header for the DK."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output header path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing generated header.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output.resolve()

    if output.exists() and not args.force:
        print(f"ERROR: {output} already exists.")
        print("Use --force only if you intentionally want to rotate the demo public key.")
        return 1

    public_key, secret_key = generate_keypair()
    public_key = bytes(public_key)

    if len(public_key) != PK_SIZE:
        raise RuntimeError(
            f"Unexpected ML-KEM public-key size: {len(public_key)} != {PK_SIZE}"
        )

    # The current transport-only firmware cannot use the secret key.
    # Do not write it to disk or commit it to the repository.
    del secret_key

    fingerprint = hashlib.sha256(public_key).hexdigest()

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_header(public_key, fingerprint), encoding="utf-8")

    print(f"Generated: {output}")
    print(f"Public-key size: {len(public_key)} bytes")
    print(f"SHA-256 fingerprint: {fingerprint}")
    print("The secret key was not persisted.")
    print("The firmware remains a BLE/GATT transport validation demo.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
